WIP: Enhancement/test suite added
johnsylvain/reddit-showerthoughts-newtab pull request #5
Opened 2017-10-13 04:37 UTC by ypahalajani

1. Made App modular (still in progress)
2. Wrote a pure function for fetching data so that it can be easily tested

2017-10-13 04:40 UTC, ypahalajani commented
Address #4 
@johnsylvain , please review and let me know if I am going in the right direction. Also, I'll add a readme for running test cases. Currently, you just need to run **SpecRunner.html** (in **tests** folder) in browser. You'll see the Test Suite Status in browser.
I'll add more test cases.

2017-10-14 14:19 UTC, johnsylvain commented
Has this been tested in the browser to ensure there are no breaking issues?

2017-10-15 03:13 UTC, ypahalajani commented
Yes, It's working. And, these test cases are only for the fetchData method. I'll wind up this work by the end of today and let you know so that you can review the changes and merge this PR. Also, I'll write add a README for testing in this PR so that it becomes easy for others who'll work on it in near future.

PS: After you test the changes, let me know - what you think about the test cases. If everything is fine, I'll add more test cases.

2017-10-15 17:58 UTC, ypahalajani commented
@johnsylvain: this PR is ready to be reviewed and merged!

2017-10-17 00:58 UTC, johnsylvain requested changes

2017-10-17 00:58 UTC, johnsylvain commented on app.module.js
> +    this.fetchData('https://www.reddit.com/r/showerthoughts/hot.json?limit=300')
Use `vm` instead of `this` for consistency

2017-10-17 00:58 UTC, johnsylvain commented on tab.html
>    <script src="background.js"></script>
`background.js` only has two lines of code, let's just inline the JavaScript. Example:
```html
<script>
  var app = new App();
  app.init();
</script>
```

2017-10-17 00:58 UTC, johnsylvain commented on app.module.js
> +    const serializedState = JSON.stringify(state);
Use `var` instead of `const`. I want to eventually move the entire project to es6, but for now let's stay with es5 for consistency.

2017-10-17 01:00 UTC, johnsylvain commented
Just some minor tweaks, everything else looks good.

2017-10-17 04:24 UTC, ypahalajani commented
I've made the requested changes except for the one that said to include the two lines of app module initialization as inline script of tab.html because,

From [Chrome Extension CSP Docs](https://developer.chrome.com/extensions/contentSecurityPolicy#JSExecution), 
> Inline JavaScript will not be executed. This restriction bans both inline <script> blocks and inline event handlers (e.g. <button onclick="...">).

So, I think let's just keep it that way due to restriction. All the other changes have been updated in the PR.

BTW, I am loving this extension, Every time new tab has a new quote and that too interesting ones! :+1:

2017-10-17 23:53 UTC, johnsylvain commented on app.module.js
> +      Object.assign(vm.state.cachedPosts, {
`vm.state.cache` is initially set to `undefined`, therefore `Object.assign` can throw an error in some cases (when `localStorage` is cleared). Please revert this to the original method:

```js
vm.state.cachedPosts = {
  data: res,
  expirationCacheTime: new Date().addHours(1)
}
```

2017-10-18 16:00 UTC, ypahalajani commented
@johnsylvain: Indeed, you are right. Reverted the *Object.assign* change to previous way.

2017-10-18 23:55 UTC, johnsylvain approved these changes

2017-10-18 23:55 UTC, merged